---
- name: Playbook to setup a Red Hat Satellite Environment within AWS
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Create VPC "{{ vpc_name }}" in region {{ region }}
      ec2_vpc_net:
        name: "{{ vpc_name }}"
        cidr_block: "{{ vpc_cidr_block }}"
        region: "{{ region }}"
        tenancy: default
        tags:
          Name: "{{ vpc_name }}"
      register: __vpc_info

    - name: Create internet gateway "{{ igw_name }}"
      ec2_vpc_igw:
        vpc_id: "{{ __vpc_info.vpc.id }}"
        region: "{{ region }}"
        tags:
          Name: "{{ igw_name }}"
        state: present
      register: __igw_info

    - name: Create subnet {{ subnet1_name }}
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ __vpc_info.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ subnet1_cidr }}"
        az: "{{ subnet1_az }}"
        tags:
          Name: "{{ subnet1_name }}"
      register: __subnet1_info

    - name: Create subnet {{ subnet2_name }}
      ec2_vpc_subnet:
        state: present
        vpc_id: "{{ __vpc_info.vpc.id }}"
        region: "{{ region }}"
        cidr: "{{ subnet2_cidr }}"
        az: "{{ subnet2_az }}"
        tags:
          Name: "{{ subnet2_name }}"
      register: __subnet2_info

    - name: Get route table info of {{ __vpc_info.vpc.id }}
      ec2_vpc_route_table_info:
        region: "{{ region }}"
        filters:
          vpc-id: "{{ __vpc_info.vpc.id }}"
      register: __route_table_info

    - name: Set up public subnet route table "{{ __route_table_info.route_tables[0].id }}"
      ec2_vpc_route_table:
        route_table_id: "{{ __route_table_info.route_tables[0].id }}"
        vpc_id: "{{ __vpc_info.vpc.id }}"
        region: "{{ region }}"
        lookup: id
        subnets:
          - "{{ subnet1_cidr }}"
          - "{{ subnet2_cidr }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ __igw_info.gateway_id }}"
        tags:
          Name: "{{ rtb_name }}"
      register: __route_table_info

    - name: Create ingress and egress security groups for Satellite instance
      ec2_group:
        name: "{{ sat_sg_name }}"
        description: "{{ sat_sg_description }}"
        region: "{{ region }}"
        vpc_id: "{{ __vpc_info.vpc.id }}"
        tags:
          Name: "{{ sat_sg_name }}"
        rules:
          - proto: Tcp
            ports: "{{ sat_in_tcp }}"
            cidr_ip: 0.0.0.0/0
          - proto: Udp
            ports: "{{ sat_in_udp }}"
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: Tcp
            ports: "{{ sat_eg_tcp }}"
            cidr_ip: 0.0.0.0/0
          - proto: Udp
            ports: "{{ sat_eg_udp }}"
            cidr_ip: 0.0.0.0/0

    - name: Create ingress and egress security groups for Capsule instance
      ec2_group:
        name: "{{ cap_sg_name }}"
        description: "{{ cap_sg_description }}"
        region: "{{ region }}"
        vpc_id: "{{ __vpc_info.vpc.id }}"
        tags:
          Name: "{{ cap_sg_name }}"
        rules:
          - proto: Tcp
            ports: "{{ cap_in_tcp }}"
            cidr_ip: 0.0.0.0/0
          - proto: Udp
            ports: "{{ cap_in_udp }}"
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: Tcp
            ports: "{{ cap_eg_tcp }}"
            cidr_ip: 0.0.0.0/0
          - proto: Udp
            ports: "{{ cap_eg_udp }}"
            cidr_ip: 0.0.0.0/0

    - name: Creating Amazon EC2 key pair
      ec2_key:
        name: "{{ key_name }}"
        region: "{{ region }}"
      register: ec2_key_result

    - name: Save private key
      copy: content="{{ ec2_key_result.key.private_key }}" dest="./{{ key_name }}.pem" mode=0600
      when: ec2_key_result.changed

    - name: Deploy ec2 machine on {{ subnet1_name }}
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        group: "{{ sat_sg_name }}"
        image: "{{ ami_id }}"
        instance_type: "{{ sat_instance_size }}"
        wait: true
        instance_tags:
          type: ec2instance
          Name: "{{ sat_instance_name }}"
        vpc_subnet_id: "{{ __subnet1_info.subnet.id }}"
        assign_public_ip: yes
      register: __ec2_subnet1

    - name: Deploy ec2 machine on {{ subnet2_name }}
      ec2:
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        group: "{{ cap_sg_name }}"
        image: "{{ ami_id }}"
        instance_type: "{{ cap_instance_size }}"
        wait: true
        instance_tags:
          type: ec2instance
          Name: "{{ cap_instance_name }}"
        vpc_subnet_id: "{{ __subnet2_info.subnet.id }}"
        assign_public_ip: yes
      register: __ec2_subnet2

    - name: Wait for SSH to come up ec2-{{ subnet1_name }}
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 30
        timeout: 240
      with_items: "{{ __ec2_subnet1.instances }}"
      when: "__ec2_subnet1.instances is defined"

    - name: Wait for SSH to come up ec2-{{ subnet2_name }}
      wait_for:
        host: "{{ item.public_dns_name }}"
        port: 22
        delay: 30
        timeout: 240
      with_items: "{{ __ec2_subnet2.instances }}"
      when: "__ec2_subnet2.instances is defined"

    - name: Get EC2 instances info
      ec2_instance_info:
        region: "{{ region }}"
        filters:
          "tag:Name":
            - "{{ sat_instance_name }}"
            - "{{ cap_instance_name }}"
          instance-state-name: ['running', 'stopped']
      register: __ec2_machines_info

    - name: Creating volume for the Satellite and Capsule Instance
      ec2_vol:
        volume_size: "500"
        device_name: /dev/xvdf
        volume_type: gp2
        region: "{{ region }}"
        instance: "{{ item.instance_id }}"
        delete_on_termination: true
      with_items: "{{ __ec2_machines_info.instances }}"
