---
plugin: aws_ec2
aws_access_key: "{{ aws_ak }}"
aws_secret_key: "{{ aws_sk }}"
regions:
  - us-east-1

keyed_groups:
  - key: tags
    prefix: tag
  - prefix: instance_type
    key: instance_type
  - key: placement.region
    prefix: aws_region
...
